clusterName: "rocketmq-cluster-a"

image:
  repository: "apache/rocketmq"
  pullPolicy: IfNotPresent
  tag: "4.9.7"

broker:
  size:
    master: 1
    replica: 0

  master:
    brokerRole: ASYNC_MASTER
    jvmMemory: "-Xms1g -Xmx1g"
    resources:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 200m
        memory: 1Gi

  replica:
    jvmMemory: "-Xms1g -Xmx1g"
    resources:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 50m
        memory: 1Gi

  persistence:
    enabled: true
    size: 20Gi
    #storageClass: "gp2"

  config:
    ## brokerClusterName brokerName brokerRole brokerId 由内置脚本自动生成
    deleteWhen: "04"
    fileReservedTime: "48"
    flushDiskType: "ASYNC_FLUSH"
    waitTimeMillsInSendQueue: "1000"
    #transientStorePoolEnable: "true"
    #transferMsgByHeap: "false"

  affinityOverride: {}
  tolerations: []
  nodeSelector: {}

  ## broker.readinessProbe
  readinessProbe:
    tcpSocket:
      port: main
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

nameserver:
  replicaCount: 1

  resources:
    limits:
      cpu: 1
      memory: 1Gi
      ephemeral-storage: 8Gi
    requests:
      cpu: 100m
      memory: 1Gi
      ephemeral-storage: 1Gi

  persistence:
    enabled: false
    size: 8Gi
    #storageClass: "gp2"

  affinityOverride: {}
  tolerations: []
  nodeSelector: {}

  ## nameserver.readinessProbe
  readinessProbe:
    tcpSocket:
      port: main
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

dashboard:
  enabled: true
  replicaCount: 1
  image:
    repository: "apacherocketmq/rocketmq-dashboard"
    pullPolicy: IfNotPresent
    tag: "1.0.0"

  jvm:
    maxHeapSize: 256M

  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 20m
      memory: 512Mi

  service:
    annotations: {}
    type: ClusterIP
    # nodePort: 31007

  ingress:
    enabled: true
    className: "nginx"
    annotations: {}
      # nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,124.160.30.50
    hosts:
      - host: rocketmq-dashboard.internal.local
    tls: []
    #  - secretName: example-tls
    #    hosts:
    #      - rocketmq-dashboard.example.com
