# 1、基础镜像
FROM alpine:3.20

# 2、镜像作者
LABEL maintainer="developer chenlong220192@gmail.com"

# 3、缺省语言设置
ENV LANG=C.UTF-8

# 4、更换Alpine源
RUN echo http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.20/main > /etc/apk/repositories && \
    echo http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.20/community >> /etc/apk/repositories && \
    apk update && apk upgrade && \
    apk --no-cache add ca-certificates

# 5、安装基础工具
RUN apk add curl

# 安装必要的字体和其他依赖
RUN apk add --no-cache \
    fontconfig \
    ttf-dejavu \
    ttf-droid \
    ttf-freefont \
    ttf-liberation

# 构建命令
#### docker build -f Dockerfile-origin:alpine-3.20 --rm -t origin:alpine-3.20 .
#### docker tag origin:alpine-3.20 site.mingsha:5555/origin:alpine-3.20
#### docker push site.mingsha:5555/origin:alpine-3.20
