# 1、基础镜像
FROM site.mingsha:5555/origin:alpine-3.20

# 2、安装基础工具
RUN apk add --no-cache bash make sudo docker

# 3、容器启动后执行命令
CMD ["docker","version"]

# 构建命令
#### docker build -f Dockerfile-devops-jenkins-agent:docker-alpine-3.20 --rm -t devops/jenkins-agent:docker-alpine-3.20 .
#### docker tag devops/jenkins-agent:docker-alpine-3.20 site.mingsha:5555/devops/jenkins-agent:docker-alpine-3.20
#### docker push site.mingsha:5555/devops/jenkins-agent:docker-alpine-3.20
