# node01
cluster.name: mingsha-elastic
node.name: node-01
network.host: 0.0.0.0
http.port: 9200
transport.tcp.port: 9300
discovery.seed_hosts: ["127.0.0.1:9300", "127.0.0.1:9301","127.0.0.1:9302"]
cluster.initial_master_nodes: ["node-01"]
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: certs/elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: certs/elastic-certificates.p12

# node02
cluster.name: mingsha-elastic
node.name: node-02
network.host: 0.0.0.0
http.port: 9201
transport.tcp.port: 9301
discovery.seed_hosts: ["127.0.0.1:9300", "127.0.0.1:9301","127.0.0.1:9302"]
cluster.initial_master_nodes: ["node-01"]
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: certs/elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: certs/elastic-certificates.p12

# node03
cluster.name: mingsha-elastic
node.name: node-03
network.host: 0.0.0.0
http.port: 9202
transport.tcp.port: 9302
discovery.seed_hosts: ["127.0.0.1:9300", "127.0.0.1:9301","127.0.0.1:9302"]
cluster.initial_master_nodes: ["node-01"]
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: certs/elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: certs/elastic-certificates.p12

# docker run -d --net=host --restart always -v /data/container/127.0.0.1:/usr/share/elasticsearch --name 127.0.0.1 elastic/elasticsearch:7.7.0
# docker run -d --net=host --restart always -v /data/container/127.0.0.1:/usr/share/elasticsearch --name 127.0.0.1 elastic/elasticsearch:7.7.0
# docker run -d --net=host --restart always -v /data/container/127.0.0.1:/usr/share/elasticsearch --name 127.0.0.1 elastic/elasticsearch:7.7.0

# curl -XPUT -H 'Content-Type: application/json' -u elastic 'http://127.0.0.1:9200/_xpack/security/user/elastic/_password' -d '{ "password" : "mingsha" }'
