# 1、基础镜像
FROM site.mingsha:5555/origin:alpine-3.12

# 2、安装jdk
RUN wget https://dragonwell.oss-cn-shanghai.aliyuncs.com/8.19.20/Alibaba_Dragonwell_Standard_8.19.20_x64_linux.tar.gz && \
    mkdir -p /usr/local/jdk && \
    mv Alibaba_Dragonwell_Standard_8.19.20_x64_linux.tar.gz /usr/local/jdk && \
    cd /usr/local/jdk && \
    tar -zxvf Alibaba_Dragonwell_Standard_8.19.20_x64_linux.tar.gz && \
    rm -rf Alibaba_Dragonwell_Standard_8.19.20_x64_linux.tar.gz && \
    rm -rf dragonwell-8.19.20/src.zip

# 3、变量环境
ENV JAVA_HOME=/usr/local/jdk/dragonwell-8.19.20
ENV CLASSPATH=$JAVA_HOME/bin
ENV PATH=.:$JAVA_HOME/bin:$PATH

# 4、容器启动后执行命令
CMD ["java","-version"]

# 构建命令
#### docker build -f Dockerfile-dragonwell:jdk8-alpine-3.12 --rm -t base/dragonwell:jdk8-alpine-3.12 .
#### docker tag base/dragonwell:jdk8-alpine-3.12 site.mingsha:5555/base/dragonwell:jdk8-alpine-3.12
#### docker push site.mingsha:5555/base/dragonwell:jdk8-alpine-3.12
